### ISSUE TITLE
TypeError: e.findSuperSymbol is not a function

### ISSUE THREAD

**Issue by UsedC** [EliotVU/UnrealScript-Language-Service#13]
I'm having this error repeatedly until server stops restarting. The codebase I'm working on is pretty huge

c:\Users\mssol\.vscode\extensions\eliotvu.uc-0.4.1\server\out\server.js:68
 */Object.defineProperty(e,"__esModule",{value:!0});e.RecognitionException=class extends Error{constructor(t,e,r,n){super(n),this._offendingState=-1,this._recognizer=t,this.input=e,this.ctx=r,t&&(this._offendingState=t.state)}get offendingState(){return this._offendingState}setOffendingState(t){this._offendingState=t}get expectedTokens(){if(this._recognizer)return this._recognizer.atn.getExpectedTokens(this._offendingState,this.ctx)}get context(){return this.ctx}get inputStream(){return this.input}getOffendingToken(t){if(!t||t===this._recognizer)return this.offendingToken}setOffendingToken(t,e){t===this._recognizer&&(this.offendingToken=e)}get recognizer(){return this._recognizer}}},function(t,e,r){"use strict";Object.defineProperty(e,"__esModule",{value:!0});const n=r(278),i={};class s{constructor(t,e){this.hash=t,this.text=e,i[t]=this}toString(){return this.text}}function o(t){const e=n.str(t.toLowerCase());return i[e]||new s(e,t)}

TypeError: e.findSuperSymbol is not a function
    at l.index (c:\Users\mssol\.vscode\extensions\eliotvu.uc-0.4.1\server\out\server.js:364:5417)
    at e.UCQualifiedTypeSymbol.index (c:\Users\mssol\.vscode\extensions\eliotvu.uc-0.4.1\server\out\server.js:364:2600)
    at e.UCObjectLiteral.index (c:\Users\mssol\.vscode\extensions\eliotvu.uc-0.4.1\server\out\server.js:364:21347)
    at e.UCDefaultAssignmentExpression.index (c:\Users\mssol\.vscode\extensions\eliotvu.uc-0.4.1\server\out\server.js:364:16405)
    at e.UCBlock.index (c:\Users\mssol\.vscode\extensions\eliotvu.uc-0.4.1\server\out\server.js:600:2504)
    at e.DocumentIndexer.visitDefaultPropertiesBlock (c:\Users\mssol\.vscode\extensions\eliotvu.uc-0.4.1\server\out\server.js:600:4913)
    at e.UCDefaultPropertiesBlock.accept (c:\Users\mssol\.vscode\extensions\eliotvu.uc-0.4.1\server\out\server.js:600:20680)
    at e.DocumentIndexer.visitStructBase (c:\Users\mssol\.vscode\extensions\eliotvu.uc-0.4.1\server\out\server.js:600:4642)
    at e.DocumentIndexer.visitClass (c:\Users\mssol\.vscode\extensions\eliotvu.uc-0.4.1\server\out\server.js:600:4690)
    at e.UCDocumentClassSymbol.accept (c:\Users\mssol\.vscode\extensions\eliotvu.uc-0.4.1\server\out\server.js:600:19023)
[Info  - 7:32:11 PM] Connection to server got closed. Server will restart.

**Comment by EliotVU** [comment]
Hey, thanks for reporting this issue!

My guess is that this issue is caused by an object literal where a former identifier is matched with a non-struct symbol, at least that's how I managed to reproduce this issue on my end!

**Comment by EliotVU** [comment]
I published a hotfix 0.4.2, let me know if this resolves your issue!

**Comment by UsedC** [comment]
Yes, everything works fine. Thanks a lot!
