### ISSUE TITLE
[0.4.3] "const ref" argument confusing the parser

### ISSUE THREAD

**Issue by Xymanek** [EliotVU/UnrealScript-Language-Service#14]
![image](https://user-images.githubusercontent.com/2865341/66702900-4046f900-ed15-11e9-93c3-5b60608bddd7.png)
```uc
static native function bool IsUnitInRange(const ref XComGameState_Unit SourceUnit, const ref XComGameState_Unit TargetUnit,
										  float MinRange = 0.0f, float MaxRange = 0.0f, float MaxAngle = 360.0f);

static native function bool IsUnitInRangeFromLocations(const ref XComGameState_Unit SourceUnit, const ref XComGameState_Unit TargetUnit,
										  const out TTile SourceTile, const out TTile TargetTile, 
										  float MinRange = 0.0f, float MaxRange = 0.0f, float MaxAngle = 360.0f);
```
```
Encountered an error while constructing the body for function 'XComGame.Helpers.IsUnitInRange' Error: The specified node does not exist
    at Tt.getChild (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:40:1695)
    at Tt.getRuleContext (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:40:2402)
    at Tt.functionBody (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:256:277874)
    at e.DocumentASTWalker.visitFunctionDecl (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:596:22518)
    at Tt.accept (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:256:278381)
    at e.DocumentASTWalker.visitChildren (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:600:658)
    at O.accept (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:256:252506)
    at e.DocumentASTWalker.visitChildren (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:600:658)
    at R.accept (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:256:251720)
    at e.DocumentASTWalker.visit (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:600:513)
Encountered an error while constructing the body for function 'XComGame.Helpers.XComGameState_Unit' Error: The specified node does not exist
    at Tt.getChild (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:40:1695)
    at Tt.getRuleContext (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:40:2402)
    at Tt.functionBody (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:256:277874)
    at e.DocumentASTWalker.visitFunctionDecl (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:596:22518)
    at Tt.accept (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:256:278381)
    at e.DocumentASTWalker.visitChildren (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:600:658)
    at O.accept (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:256:252506)
    at e.DocumentASTWalker.visitChildren (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:600:658)
    at R.accept (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:256:251720)
    at e.DocumentASTWalker.visit (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:600:513)
Encountered an error while constructing the body for function 'XComGame.Helpers.IsUnitInRangeFromLocations' Error: The specified node does not exist
    at Tt.getChild (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:40:1695)
    at Tt.getRuleContext (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:40:2402)
    at Tt.functionBody (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:256:277874)
    at e.DocumentASTWalker.visitFunctionDecl (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:596:22518)
    at Tt.accept (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:256:278381)
    at e.DocumentASTWalker.visitChildren (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:600:658)
    at O.accept (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:256:252506)
    at e.DocumentASTWalker.visitChildren (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:600:658)
    at R.accept (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:256:251720)
    at e.DocumentASTWalker.visit (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:600:513)
Encountered an error while constructing the body for function 'XComGame.Helpers.XComGameState_Unit' Error: The specified node does not exist
    at Tt.getChild (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:40:1695)
    at Tt.getRuleContext (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:40:2402)
    at Tt.functionBody (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:256:277874)
    at e.DocumentASTWalker.visitFunctionDecl (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:596:22518)
    at Tt.accept (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:256:278381)
    at e.DocumentASTWalker.visitChildren (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:600:658)
    at O.accept (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:256:252506)
    at e.DocumentASTWalker.visitChildren (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:600:658)
    at R.accept (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:256:251720)
    at e.DocumentASTWalker.visit (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:600:513)
Encountered an error while constructing the body for function 'XComGame.Helpers.TTile' Error: The specified node does not exist
    at Tt.getChild (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:40:1695)
    at Tt.getRuleContext (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:40:2402)
    at Tt.functionBody (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:256:277874)
    at e.DocumentASTWalker.visitFunctionDecl (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:596:22518)
    at Tt.accept (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:256:278381)
    at e.DocumentASTWalker.visitChildren (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:600:658)
    at O.accept (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:256:252506)
    at e.DocumentASTWalker.visitChildren (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:600:658)
    at R.accept (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:256:251720)
    at e.DocumentASTWalker.visit (c:\Users\xyman\.vscode\extensions\eliotvu.uc-0.4.3\server\out\server.js:600:513)
Helpers: Walking time 17.128762990236282
Helpers: linking time 2.1040569841861725
[Helpers]: post linking time 6.587505012750626
```

**Comment by EliotVU** [comment]
Thanks! This has been fixed in the next update(0.5) :)

I'm assuming this is a feature shared between some of the UE3 licensees.
