### ISSUE TITLE
[Bug]: Parser breaks on documents with special characters

### ISSUE THREAD

**Issue by EliotVU** [EliotVU/UnrealScript-Language-Service#162]
### Describe the bug

When the parser stumbles on special characters it will fail with the following error:
```unrealscript
Processing pending document "file:///c%3A/.../Engine/Classes/PlaylistParserBase.uc":1, source:change.
Invalidating document "PlaylistParserBase".
building document PlaylistParserBase
PredictionMode SLL has failed, rolling back to LL.
An error was thrown while parsing document: "file:///c%3A/.../Engine/Classes/PlaylistParserBase.uc" Error: cannot consume EOF
    at UCTokenStream.consume (c:\Projecten\UnrealScriptLang\out\server.js:28905:19)
    at UCParser.skipLine (c:\Projecten\UnrealScriptLang\out\server.js:5417:25)
    at UCParser.directive (c:\Projecten\UnrealScriptLang\out\server.js:5544:22)
    at UCParser.member (c:\Projecten\UnrealScriptLang\out\server.js:5711:30)
    at UCParser.program (c:\Projecten\UnrealScriptLang\out\server.js:5581:42)
    at UCDocument.build (c:\Projecten\UnrealScriptLang\out\server.js:20658:34)
    at indexDocument (c:\Projecten\UnrealScriptLang\out\server.js:24237:18)
    at Object.next (c:\Projecten\UnrealScriptLang\out\server.js:26656:41)
```

Appears to be caused by the following code:
```
     SpecialChars(0)=(Plain="&",Coded="&amp;")
     SpecialChars(1)=(Plain=""",Coded="&quot;")
     SpecialChars(2)=(Plain=" ",Coded="&nbsp;")
     SpecialChars(3)=(Plain="<",Coded="&lt;")
     SpecialChars(4)=(Plain=">",Coded="&gt;")
     SpecialChars(5)=(Plain="�",Coded="&copy;")
     SpecialChars(6)=(Plain="�",Coded="&#8482;")
     SpecialChars(7)=(Plain="�",Coded="&reg;")
     SpecialChars(8)=(Plain="'",Coded="&apos;")
```

**Comment by EliotVU** [comment]
Weird, as far as UT2004 goes, the string is actually escaped:
```
     SpecialChars(0)=(Plain="&",Coded="&amp;")
     SpecialChars(1)=(Plain="\"",Coded="&quot;")
     SpecialChars(2)=(Plain=" ",Coded="&nbsp;")
     SpecialChars(3)=(Plain="<",Coded="&lt;")
     SpecialChars(4)=(Plain=">",Coded="&gt;")
     SpecialChars(5)=(Plain="©",Coded="&copy;")
     SpecialChars(6)=(Plain="™",Coded="&#8482;")
     SpecialChars(7)=(Plain="®",Coded="&reg;")
     SpecialChars(8)=(Plain="'",Coded="&apos;")
```

**Comment by PolaricEntropy** [comment]
I had this happen in the following file, that does not seem to contain special characters:  [DeusExText.zip](https://github.com/EliotVU/UnrealScript-Language-Service/files/12899162/DeusExText.zip)

**Comment by Shtoyan** [comment]
> I had this happen in the following file, that does not seem to contain special characters: [DeusExText.zip](https://github.com/EliotVU/UnrealScript-Language-Service/files/12899162/DeusExText.zip)

Did a quick check from interest - extension starts to work when you comment `exec` directive line.

**Comment by EliotVU** [comment]
@Shtoyan or by appending ```function test();``` after the exec line seems to work too, I suppose this is because ANTLR is then able to find an alternative rule to match :|

FYI: This is caused by the hacky-code in the ANTLR parser https://github.com/EliotVU/UnrealScript-Language-Service/blob/22b6fbb79476f374c2d7b7c5884cacb7bc1e946c/grammars/UCParser.g4#L12
https://github.com/EliotVU/UnrealScript-Language-Service/blob/22b6fbb79476f374c2d7b7c5884cacb7bc1e946c/grammars/UCParser.g4#L239

**Comment by EliotVU** [comment]
Unfortunately I have to admit I'm unable to fix this issue in a way that ANTLR would understand.

A proper solution to this #directive parsing would be to switch the lexer's channel when a statement directive has been detected, but ANTLR is incapable of this as far as I know.

**Comment by Shtoyan** [comment]
No way to just ignore all `#directives` during parsing/lexing?
