### ISSUE TITLE
[Bug]:  Error: cannot consume EOF

### ISSUE THREAD

**Issue by PolaricEntropy** [EliotVU/UnrealScript-Language-Service#184]
### Describe the bug

When enabling to index all workspace files I noticed some errors in the output.

An error was thrown while parsing document: "file:///c%3A/repos/dx-revision/RevisionSrc/DeusExText/Classes/DeusExText.uc" Error: cannot consume EOF
    at o.consume (c:\Users\bjorn\.vscode\extensions\eliotvu.uc-0.7.1\out\vendor.js:2:377576)
    at I.skipLine (c:\Users\bjorn\.vscode\extensions\eliotvu.uc-0.7.1\out\server.js:2:118502)
    at I.directive (c:\Users\bjorn\.vscode\extensions\eliotvu.uc-0.7.1\out\server.js:2:126039)
    at I.member (c:\Users\bjorn\.vscode\extensions\eliotvu.uc-0.7.1\out\server.js:2:128930)
    at I.program (c:\Users\bjorn\.vscode\extensions\eliotvu.uc-0.7.1\out\server.js:2:127504)
    at e.UCDocument.build (c:\Users\bjorn\.vscode\extensions\eliotvu.uc-0.7.1\out\server.js:2:524428)
    at l (c:\Users\bjorn\.vscode\extensions\eliotvu.uc-0.7.1\out\server.js:2:586153)
    at Object.next (c:\Users\bjorn\.vscode\extensions\eliotvu.uc-0.7.1\out\server.js:2:627148)
PredictionMode SLL has failed, rolling back to LL.
DeusExText: transforming time 0.7032999992370605
DeusExText: build time: 0.9203999936580658; indexing time 0.0020999908447265625

Could this be due to line endings or encoding? I have around 45 files with this error. Here's one of the files: [DeusExText.zip](https://github.com/EliotVU/UnrealScript-Language-Service/files/12899162/DeusExText.zip)

**Comment by PolaricEntropy** [comment]
Duplicate of #162
